# Generated by Django 5.1.7 on 2025-03-26 13:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("content", models.TextField()),
                ("category", models.CharField(max_length=50)),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="blog/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CareerAdvice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("content", models.TextField()),
                ("category", models.CharField(max_length=50)),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="career_advice/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Career Advice",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResumeExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="resume_examples/")),
                ("pdf_file", models.FileField(upload_to="resume_examples/pdfs/")),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResumeTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("professional", "Professional"),
                            ("creative", "Creative"),
                            ("modern", "Modern"),
                            ("simple", "Simple"),
                            ("executive", "Executive"),
                        ],
                        max_length=20,
                    ),
                ),
                ("preview_image", models.ImageField(upload_to="template_previews/")),
                ("thumbnail", models.ImageField(upload_to="template_thumbnails/")),
                ("is_premium", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("description", models.TextField()),
                ("color_schemes", models.JSONField(default=list)),
                ("font_pairs", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="education",
            options={
                "ordering": ["-start_date", "order"],
                "verbose_name": "Education",
                "verbose_name_plural": "Education",
            },
        ),
        migrations.AlterModelOptions(
            name="language",
            options={
                "ordering": ["name"],
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
            },
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={
                "ordering": ["name"],
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
            },
        ),
        migrations.AlterModelOptions(
            name="workexperience",
            options={
                "ordering": ["-start_date", "order"],
                "verbose_name": "Work Experience",
                "verbose_name_plural": "Work Experiences",
            },
        ),
        migrations.RemoveField(
            model_name="education",
            name="city",
        ),
        migrations.RemoveField(
            model_name="education",
            name="country",
        ),
        migrations.RemoveField(
            model_name="education",
            name="current_school",
        ),
        migrations.RemoveField(
            model_name="education",
            name="school",
        ),
        migrations.RemoveField(
            model_name="workexperience",
            name="city",
        ),
        migrations.RemoveField(
            model_name="workexperience",
            name="country",
        ),
        migrations.RemoveField(
            model_name="workexperience",
            name="current_job",
        ),
        migrations.RemoveField(
            model_name="workexperience",
            name="employer",
        ),
        migrations.RemoveField(
            model_name="workexperience",
            name="job_title",
        ),
        migrations.AddField(
            model_name="education",
            name="achievements",
            field=models.JSONField(
                blank=True, default=list, help_text="List of achievements, honors, etc."
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="activities",
            field=models.TextField(
                blank=True, help_text="Extracurricular activities and societies"
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="education",
            name="field_of_study",
            field=models.CharField(
                blank=True, help_text="Major or field of study", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="gpa",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Grade Point Average (optional)",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="institution",
            field=models.CharField(
                blank=True,
                help_text="Name of the school or university",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="is_current",
            field=models.BooleanField(
                default=False, help_text="Check if currently studying"
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="City, State/Province, Country",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="education",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="is_public",
            field=models.BooleanField(
                default=False, help_text="Make this resume visible to others"
            ),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="achievements",
            field=models.JSONField(
                blank=True, default=list, help_text="List of key achievements"
            ),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="company",
            field=models.CharField(
                blank=True, help_text="Name of the company", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="company_website",
            field=models.URLField(
                blank=True, help_text="Company website URL (optional)"
            ),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("full_time", "Full-time"),
                    ("part_time", "Part-time"),
                    ("contract", "Contract"),
                    ("internship", "Internship"),
                    ("freelance", "Freelance"),
                ],
                default="full_time",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="is_current",
            field=models.BooleanField(
                default=False, help_text="Check if this is your current position"
            ),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="City, Country or Remote",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="position",
            field=models.CharField(
                blank=True, help_text="Your job title", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="degree",
            field=models.CharField(
                blank=True,
                choices=[
                    ("high_school", "High School"),
                    ("associate", "Associate Degree"),
                    ("bachelor", "Bachelor's Degree"),
                    ("master", "Master's Degree"),
                    ("doctorate", "Doctorate"),
                    ("certification", "Certification"),
                    ("diploma", "Diploma"),
                    ("other", "Other"),
                ],
                help_text="Type of degree received",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="description",
            field=models.TextField(
                blank=True, help_text="Additional details about your studies"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="end_date",
            field=models.DateField(
                blank=True, help_text="Leave blank if currently studying", null=True
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="education",
                to="home.resume",
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="start_date",
            field=models.DateField(help_text="Start date of education"),
        ),
        migrations.AlterField(
            model_name="language",
            name="level",
            field=models.CharField(
                choices=[
                    ("elementary", "Elementary"),
                    ("limited", "Limited Working"),
                    ("professional", "Professional Working"),
                    ("full", "Full Professional"),
                    ("native", "Native/Bilingual"),
                ],
                default="elementary",
                help_text="Proficiency level",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(help_text="Language name", max_length=50),
        ),
        migrations.AlterField(
            model_name="skill",
            name="level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                    ("expert", "Expert"),
                ],
                default="intermediate",
                help_text="Proficiency level",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(help_text="Name of the skill", max_length=50),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="description",
            field=models.TextField(
                help_text="Describe your responsibilities and achievements"
            ),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Leave blank if this is your current position",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_experiences",
                to="home.resume",
            ),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="start_date",
            field=models.DateField(help_text="Start date of employment"),
        ),
        migrations.CreateModel(
            name="ResumeSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("personal", "Personal Information"),
                            ("summary", "Professional Summary"),
                            ("experience", "Work Experience"),
                            ("education", "Education"),
                            ("skills", "Skills"),
                            ("languages", "Languages"),
                            ("certifications", "Certifications"),
                            ("projects", "Projects"),
                            ("custom", "Custom Section"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "company",
                    models.CharField(
                        blank=True,
                        help_text="Name of the company",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="Your job title",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="City, Country or Remote",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Start date of employment", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank if current position",
                        null=True,
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        help_text="Check if this is your current position",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Describe your responsibilities and achievements",
                    ),
                ),
                (
                    "achievements",
                    models.JSONField(
                        blank=True, default=list, help_text="List of key achievements"
                    ),
                ),
                (
                    "company_website",
                    models.URLField(
                        blank=True, help_text="Company website URL (optional)"
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full_time", "Full-time"),
                            ("part_time", "Part-time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                            ("freelance", "Freelance"),
                        ],
                        default="full_time",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="home.resume",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resume Section",
                "verbose_name_plural": "Resume Sections",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("technologies", models.JSONField(default=list)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="home.resumesection",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("issuing_organization", models.CharField(max_length=100)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("credential_id", models.CharField(blank=True, max_length=100)),
                ("credential_url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="home.resumesection",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date"],
            },
        ),
        migrations.AddField(
            model_name="language",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="languages",
                to="home.resumesection",
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="home.resumesection",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="language",
            unique_together={("section", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="skill",
            unique_together={("section", "name")},
        ),
        migrations.CreateModel(
            name="SavedSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.JSONField()),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("personal", "Personal Information"),
                            ("summary", "Professional Summary"),
                            ("experience", "Work Experience"),
                            ("education", "Education"),
                            ("skills", "Skills"),
                            ("languages", "Languages"),
                            ("certifications", "Certifications"),
                            ("projects", "Projects"),
                            ("custom", "Custom Section"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemplateSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("html_content", models.TextField()),
                ("css_content", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.resumetemplate",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="language",
            name="resume",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="resume",
        ),
    ]
