# Generated by Django 5.1.7 on 2025-03-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_coverlettertemplate_cvtemplate_coverletter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resumetemplate",
            name="color_schemes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resumetemplate",
            name="font_pairs",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
