# Generated by Django 5.1.7 on 2025-04-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_careercategory_newslettersubscription_careerarticle"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumetemplate",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
