# Generated by Django 5.1.7 on 2025-04-08 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_alter_blogpost_options_blogpost_author_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="industry",
            options={"ordering": ["name"], "verbose_name_plural": "Industries"},
        ),
        migrations.RemoveField(
            model_name="industry",
            name="order",
        ),
        migrations.AddField(
            model_name="industry",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="industry",
            name="icon",
            field=models.CharField(
                blank=True, help_text="Bootstrap icon class", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="industry",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name="JobTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("featured", models.BooleanField(default=False)),
                (
                    "industry",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_titles",
                        to="home.industry",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
