# Generated by Django 5.1.7 on 2025-04-08 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_alter_industry_options_remove_industry_order_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resumeexample",
            old_name="is_featured",
            new_name="featured",
        ),
        migrations.RemoveField(
            model_name="resumeexample",
            name="category",
        ),
        migrations.RemoveField(
            model_name="resumeexample",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="resumeexample",
            name="pdf_file",
        ),
        migrations.RemoveField(
            model_name="resumeexample",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="resumeexample",
            name="experience_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("entry-level", "Entry Level"),
                    ("mid-level", "Mid Level"),
                    ("senior", "Senior"),
                    ("executive", "Executive"),
                    ("student", "Student"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resumeexample",
            name="industry",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="examples",
                to="home.industry",
            ),
        ),
        migrations.AddField(
            model_name="resumeexample",
            name="job_title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="examples",
                to="home.jobtitle",
            ),
        ),
        migrations.AddField(
            model_name="resumeexample",
            name="pdf",
            field=models.FileField(blank=True, upload_to="resume_examples/pdf/"),
        ),
        migrations.AddField(
            model_name="resumeexample",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
