# Generated by Django 5.1.7 on 2025-04-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_rename_is_featured_resumeexample_featured_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resumeexample",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
