# Generated by Django 5.1.7 on 2025-04-08 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_alter_resumeexample_slug"),
        ("templates_app", "0002_resumetemplate_category_resumetemplate_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatesection",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="templates_app.resumetemplate",
            ),
        ),
        migrations.DeleteModel(
            name="ResumeTemplate",
        ),
    ]
