# Generated by Django 5.1.7 on 2025-04-02 07:19

import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(unique=True)),
                (
                    "icon",
                    models.CharField(
                        help_text="Font Awesome icon class", max_length=50
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Template Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ResumeTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("preview_image", models.ImageField(upload_to="template_previews/")),
                (
                    "thumbnail",
                    models.ImageField(blank=True, upload_to="template_thumbnails/"),
                ),
                ("has_photo", models.BooleanField(default=True)),
                ("is_ats_friendly", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_premium", models.BooleanField(default=False)),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "html_structure",
                    models.TextField(help_text="HTML structure with placeholders"),
                ),
                (
                    "css_template",
                    models.TextField(help_text="CSS styles for the template"),
                ),
                ("popularity", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="templates", to="templates_app.templatecategory"
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-popularity", "name"],
            },
        ),
        migrations.CreateModel(
            name="TemplateColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "primary_color",
                    colorfield.fields.ColorField(
                        default="#2D9CDB", image_field=None, max_length=25, samples=None
                    ),
                ),
                (
                    "secondary_color",
                    colorfield.fields.ColorField(
                        default="#333333", image_field=None, max_length=25, samples=None
                    ),
                ),
                (
                    "accent_color",
                    colorfield.fields.ColorField(
                        default="#F2F2F2", image_field=None, max_length=25, samples=None
                    ),
                ),
                (
                    "text_color",
                    colorfield.fields.ColorField(
                        default="#333333", image_field=None, max_length=25, samples=None
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colors",
                        to="templates_app.resumetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "name"],
                "unique_together": {("template", "name")},
            },
        ),
        migrations.CreateModel(
            name="UserTemplateSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "color_scheme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="templates_app.templatecolor",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="templates_app.resumetemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-selected_at"],
            },
        ),
        migrations.CreateModel(
            name="TemplateSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("contact", "Contact Information"),
                            ("summary", "Professional Summary"),
                            ("experience", "Work Experience"),
                            ("education", "Education"),
                            ("skills", "Skills"),
                            ("languages", "Languages"),
                            ("certifications", "Certifications"),
                            ("projects", "Projects"),
                            ("awards", "Awards"),
                            ("publications", "Publications"),
                            ("references", "References"),
                            ("custom", "Custom Section"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_required", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="templates_app.resumetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("template", "section_type")},
            },
        ),
    ]
