# Generated by Django 5.1.7 on 2025-04-08 12:14

import django.db.models.deletion
import imagekit.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="resumetemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("simple", "Simple"),
                    ("professional", "Professional"),
                    ("modern", "Modern"),
                    ("creative", "Creative"),
                ],
                default="simple",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="resumetemplate",
            name="color",
            field=models.CharField(
                choices=[
                    ("blue", "Blue"),
                    ("black", "Black"),
                    ("gray", "Gray"),
                    ("green", "Green"),
                    ("burgundy", "Burgundy"),
                    ("navy", "Navy"),
                ],
                default="blue",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="resumetemplate",
            name="color_scheme",
            field=models.CharField(default="blue", max_length=50),
        ),
        migrations.AddField(
            model_name="resumetemplate",
            name="content",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="resumetemplate",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="resumetemplate",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resumetemplate",
            name="style",
            field=models.CharField(
                choices=[
                    ("executive", "Executive"),
                    ("corporate", "Corporate"),
                    ("classic", "Classic"),
                    ("minimalist", "Minimalist"),
                    ("elegant", "Elegant"),
                    ("bold", "Bold"),
                    ("modern-executive", "Modern Executive"),
                    ("two-column", "Two Column"),
                ],
                default="classic",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="resumetemplate",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resume_template",
                to="templates_app.resumetemplate",
            ),
        ),
        migrations.AddField(
            model_name="resumetemplate",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="resumetemplate",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resumes_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="resumetemplate",
            name="popularity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="resumetemplate",
            name="preview_image",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, null=True, upload_to="template_previews"
            ),
        ),
    ]
