# Generated by Django 5.1.7 on 2025-04-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumetemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("simple", "Simple"),
                    ("professional", "Professional"),
                    ("modern", "Modern"),
                    ("creative", "Creative"),
                ],
                default="simple",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="resumetemplate",
            name="color",
            field=models.CharField(
                choices=[
                    ("blue", "Blue"),
                    ("black", "Black"),
                    ("gray", "Gray"),
                    ("green", "Green"),
                    ("burgundy", "Burgundy"),
                    ("navy", "Navy"),
                ],
                default="blue",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="resumetemplate",
            name="style",
            field=models.CharField(
                choices=[
                    ("classic", "Classic"),
                    ("executive", "Executive"),
                    ("corporate", "Corporate"),
                    ("minimalist", "Minimalist"),
                    ("elegant", "Elegant"),
                    ("bold", "Bold"),
                ],
                default="classic",
                max_length=20,
            ),
        ),
    ]
