# Generated by Django 5.1.7 on 2025-04-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_app", "0002_resumetemplate_category_resumetemplate_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumetemplate",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
