# Generated by Django 5.1.7 on 2025-04-04 14:09

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_app", "0004_resumetemplate_color_scheme"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumetemplate",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="resumetemplate",
            name="headline",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resumetemplate",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="resumetemplate",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None, unique=True
            ),
        ),
        migrations.AddField(
            model_name="resumetemplate",
            name="summary",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
