# Generated by Django 5.1.7 on 2025-04-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("templates_app", "0005_resumetemplate_email_resumetemplate_headline_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resumetemplate",
            name="email",
        ),
        migrations.RemoveField(
            model_name="resumetemplate",
            name="headline",
        ),
        migrations.RemoveField(
            model_name="resumetemplate",
            name="location",
        ),
        migrations.RemoveField(
            model_name="resumetemplate",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="resumetemplate",
            name="summary",
        ),
    ]
