# Generated by Django 5.1.7 on 2025-04-03 12:23

import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_resumesection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Template Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="certification",
            options={"ordering": ["order", "name"]},
        ),
        migrations.AlterModelOptions(
            name="education",
            options={"ordering": ["order", "-start_date"]},
        ),
        migrations.AlterModelOptions(
            name="experience",
            options={"ordering": ["order", "-start_date"]},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["order", "title"]},
        ),
        migrations.RenameField(
            model_name="experience",
            old_name="title",
            new_name="position",
        ),
        migrations.RemoveField(
            model_name="education",
            name="gpa",
        ),
        migrations.RemoveField(
            model_name="project",
            name="current",
        ),
        migrations.AlterField(
            model_name="certification",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="education",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="education",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="educations",
                to="resume.resume",
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="language",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="language",
            name="proficiency",
            field=models.CharField(
                choices=[
                    ("elementary", "Elementary"),
                    ("limited", "Limited Working"),
                    ("professional", "Professional Working"),
                    ("full_professional", "Full Professional"),
                    ("native", "Native/Bilingual"),
                ],
                default="professional",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="skill",
            name="level",
            field=models.IntegerField(
                choices=[
                    (1, "Beginner"),
                    (2, "Intermediate"),
                    (3, "Advanced"),
                    (4, "Expert"),
                    (5, "Master"),
                ],
                default=3,
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="skill",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("job_title", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.CharField(blank=True, max_length=200)),
                ("website", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                ("github", models.URLField(blank=True)),
                ("summary", models.TextField(blank=True)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_images/"
                    ),
                ),
                (
                    "resume",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_info",
                        to="resume.resume",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemplateColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "color_code",
                    colorfield.fields.ColorField(
                        default="#FFFFFF", image_field=None, max_length=25, samples=None
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colors",
                        to="resume.resume",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_premium", models.BooleanField(default=False)),
                ("subscription_expires", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
