# Generated by Django 5.1.7 on 2025-04-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0005_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="headline",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="summary",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
