# Generated by Django 5.1.7 on 2025-04-08 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0006_resume_email_resume_headline_resume_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experiences",
                to="resume.resumetemplate",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="resume.resumetemplate",
            ),
        ),
        migrations.AlterField(
            model_name="certification",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certifications",
                to="resume.resumetemplate",
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="resume",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_info",
                to="resume.resumetemplate",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="resume.resumetemplate",
            ),
        ),
        migrations.AlterField(
            model_name="templatecolor",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="colors",
                to="resume.resumetemplate",
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="educations",
                to="resume.resumetemplate",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="languages",
                to="resume.resumetemplate",
            ),
        ),
        migrations.DeleteModel(
            name="Resume",
        ),
    ]
