# Generated by Django 5.1.7 on 2025-03-28 07:35

import colorfield.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0002_remove_activitylog_user_remove_jobapplication_user_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("preview_image", models.ImageField(upload_to="template_previews/")),
                (
                    "html_structure",
                    models.TextField(
                        help_text="HTML structure with placeholders for resume data"
                    ),
                ),
                ("css", models.TextField(help_text="CSS styles for the template")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("professional", "Professional"),
                            ("creative", "Creative"),
                            ("simple", "Simple"),
                            ("modern", "Modern"),
                            ("executive", "Executive"),
                        ],
                        max_length=20,
                    ),
                ),
                ("has_photo", models.BooleanField(default=True)),
                ("is_premium", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("allows_color_customization", models.BooleanField(default=True)),
                ("allows_font_customization", models.BooleanField(default=True)),
                ("allows_section_reordering", models.BooleanField(default=True)),
                (
                    "primary_color",
                    colorfield.fields.ColorField(
                        default="#2D3E50", image_field=None, max_length=25, samples=None
                    ),
                ),
                (
                    "secondary_color",
                    colorfield.fields.ColorField(
                        default="#3498DB", image_field=None, max_length=25, samples=None
                    ),
                ),
                (
                    "text_color",
                    colorfield.fields.ColorField(
                        default="#333333", image_field=None, max_length=25, samples=None
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="UserTemplateSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_color",
                    colorfield.fields.ColorField(
                        blank=True,
                        default=None,
                        image_field=None,
                        max_length=25,
                        null=True,
                        samples=None,
                    ),
                ),
                (
                    "secondary_color",
                    colorfield.fields.ColorField(
                        blank=True,
                        default=None,
                        image_field=None,
                        max_length=25,
                        null=True,
                        samples=None,
                    ),
                ),
                (
                    "text_color",
                    colorfield.fields.ColorField(
                        blank=True,
                        default=None,
                        image_field=None,
                        max_length=25,
                        null=True,
                        samples=None,
                    ),
                ),
                (
                    "font_family",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("selected_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.resumetemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "template")},
            },
        ),
        migrations.DeleteModel(
            name="ActivityLog",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
        migrations.DeleteModel(
            name="SavedSection",
        ),
        migrations.DeleteModel(
            name="Subscription",
        ),
        migrations.DeleteModel(
            name="Template",
        ),
        migrations.AlterModelOptions(
            name="jobapplication",
            options={"ordering": ["-date_updated"]},
        ),
        migrations.RenameField(
            model_name="userdashboardsettings",
            old_name="last_login",
            new_name="updated_at",
        ),
        migrations.RemoveField(
            model_name="jobapplication",
            name="applied_date",
        ),
        migrations.RemoveField(
            model_name="jobapplication",
            name="position",
        ),
        migrations.RemoveField(
            model_name="jobapplication",
            name="resume",
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="contact_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="date_applied",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="date_saved",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="follow_up_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="follow_up_reminder",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="job_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="job_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="job_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="salary_range",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userdashboardsettings",
            name="accent_color",
            field=colorfield.fields.ColorField(
                default="#2D9CDB", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AddField(
            model_name="userdashboardsettings",
            name="application_reminders",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userdashboardsettings",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userdashboardsettings",
            name="default_layout",
            field=models.CharField(
                choices=[
                    ("grid", "Grid View"),
                    ("list", "List View"),
                    ("compact", "Compact View"),
                ],
                default="grid",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userdashboardsettings",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userdashboardsettings",
            name="resume_update_reminders",
            field=models.BooleanField(
                default=True, help_text="Remind to update resume periodically"
            ),
        ),
        migrations.AddField(
            model_name="userdashboardsettings",
            name="show_ai_suggestions",
            field=models.BooleanField(
                default=True, help_text="Show AI-powered suggestions"
            ),
        ),
        migrations.AddField(
            model_name="userdashboardsettings",
            name="show_job_applications",
            field=models.BooleanField(
                default=True, help_text="Show job application tracking"
            ),
        ),
        migrations.AddField(
            model_name="userdashboardsettings",
            name="show_resume_stats",
            field=models.BooleanField(
                default=True, help_text="Show resume view and download statistics"
            ),
        ),
        migrations.AddField(
            model_name="userdashboardsettings",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboard_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="company",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("saved", "Saved"),
                    ("applied", "Applied"),
                    ("interviewing", "Interviewing"),
                    ("offer", "Offer Received"),
                    ("accepted", "Offer Accepted"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="saved",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userdashboardsettings",
            name="notification_enabled",
            field=models.BooleanField(
                default=True, help_text="Master toggle for all notifications"
            ),
        ),
        migrations.AlterField(
            model_name="userdashboardsettings",
            name="theme",
            field=models.CharField(
                choices=[
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("system", "System Default"),
                ],
                default="light",
                max_length=10,
            ),
        ),
    ]
