# Generated by Django 5.1.7 on 2025-04-02 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_resumetemplate_usertemplateselection_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserTemplateSelection",
        ),
    ]
