# Generated by Django 5.1.7 on 2025-03-26 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_email_alter_user_groups_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("nairobi", "Nairobi"),
                            ("lagos", "Lagos"),
                            ("cairo", "Cairo"),
                            ("accra", "Accra"),
                            ("johannesburg", "Johannesburg"),
                            ("casablanca", "Casablanca"),
                            ("dakar", "Dakar"),
                            ("addis-ababa", "Addis Ababa"),
                            ("kampala", "Kampala"),
                            ("kigali", "Kigali"),
                            ("dar-es-salaam", "Dar es Salaam"),
                            ("lusaka", "Lusaka"),
                            ("harare", "Harare"),
                            ("windhoek", "Windhoek"),
                            ("gaborone", "Gaborone"),
                        ],
                        max_length=50,
                    ),
                ),
                ("preview_image", models.ImageField(upload_to="template_previews/")),
                ("html_template", models.FileField(upload_to="template_files/")),
                ("css_template", models.FileField(upload_to="template_files/")),
                ("users_count", models.IntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.user"
            ),
        ),
        migrations.AlterField(
            model_name="securityquestion",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.user"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.user"
            ),
        ),
    ]
