# Generated by Django 5.1.7 on 2025-04-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_delete_resumetemplate_alter_user_managers_and_more"),
        ("templates_app", "0002_resumetemplate_category_resumetemplate_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="purchased_templates",
            field=models.ManyToManyField(
                blank=True,
                related_name="purchased_by",
                to="templates_app.resumetemplate",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="subscription_active_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
